### ISSUE TITLE
Applying either the kotlin-jvm other kapt-plugin with a version above 1.3.72 results in invalid bytecode generation

### ISSUE THREAD

**Issue by itsTyrion** [matfax/klassindex#13]
With both plugins active, a call to `KlassIndex.getAnnotated(Register::class)` correctly generates `KlassIndex.INSTANCE.getAnnotated`. 
However, bumping either (or both) to 1.4 or 1.4.10 results in a call to `KlassIndex.INSTANCE.getAnnotated-pe_2wiA` - which obviously doesn't exist, causing a `NoSuchMethodError`
Snippet: 
![image](https://user-images.githubusercontent.com/17730120/97639630-3e92c500-1a3f-11eb-9e0c-291f7e4542d5.png)

All builds were done using `gradle clean shadowJar`.

**Comment by matfax** [comment]
@itsTyrion Thank you for reporting this issue. I've updated all dependencies with prerelease `4.1.0-rc.1`.
Could you try the same again with this version and report back to me if it resolved?

**Comment by itsTyrion** [comment]
First of all, I'm super sorry for taking so long to reply after you fixed the issue after not even 24h. I simply forgot about it because I had quite a few things going on. :/ 
Everythings working just fine. Tested with Gradle 6.6.1, Shadow 6.1.0 ("Gradle shadowJar"), and Kotlin/Kotlin std/kapt 1.4.10

**Comment by itsTyrion** [comment]
fixed
