### ISSUE TITLE
Is there any chance to get this library with kotlin 1.5.0/1.5.10 ? Or any updates?

### ISSUE THREAD

**Issue by InsanusMokrassar** [matfax/klassindex#22]

**Comment by itsTyrion** [comment]
I'm building this with the kotlin dependency excluded so my project's version is used. 
No issues over the last year.
gradle: `implementation('com.github.matfax.klassindex:library:4.+') { exclude group: 'org.jetbrains.kotlin' }`
maven: should work, haven't tried.
