### ISSUE TITLE
4.1.0 build failed on jitpack

### ISSUE THREAD

**Issue by itsTyrion** [matfax/klassindex#49]
I just wanted to grab this from jitpack and noticed that the 4.1.0 build is on red:
https://jitpack.io/com/github/matfax/klassindex/4.1.0/build.log
![image](https://github.com/matfax/klassindex/assets/17730120/183a2fa3-433f-4a1e-97af-6621692d7a86)

Looks like Jitpack is trying to build it with Java 8 instead of 11, causing the vanniktech plugin to nope out.

**Comment by matfax** [comment]
Version 4.1+ is not maintained for Jitpack builds anymore. Jitpack can be removed. The prebuilt package is available on Maven Central.
